using Sap.Data.Hana;

using var connection = new HanaConnection(Environment.GetEnvironmentVariable("MIGRATOR_HANA")
    ?? throw new InvalidOperationException("MIGRATOR_HANA must identify the disposable CI database."));
connection.Open();
void Execute(string sql)
{
    using var command = connection.CreateCommand();
    command.CommandText = sql;
    command.ExecuteNonQuery();
}
object Scalar(string sql)
{
    using var command = connection.CreateCommand();
    command.CommandText = sql;
    return command.ExecuteScalar();
}
Execute("CREATE SCHEMA MIGRATOR_QUALIFICATION");
try
{
    Execute("CREATE ROW TABLE MIGRATOR_QUALIFICATION.ITEMS (ID INTEGER GENERATED BY DEFAULT AS IDENTITY, LABEL NVARCHAR(40) DEFAULT 'initial', CONSTRAINT PK_ITEMS PRIMARY KEY (ID), CONSTRAINT UQ_LABEL UNIQUE (LABEL))");
    Execute("INSERT INTO MIGRATOR_QUALIFICATION.ITEMS (LABEL) VALUES ('kept')");
    if (Convert.ToInt32(Scalar("SELECT COUNT(*) FROM MIGRATOR_QUALIFICATION.ITEMS")) != 1)
        throw new Exception("Inserted row missing.");
    using (var transaction = connection.BeginTransaction())
    {
        using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = "INSERT INTO MIGRATOR_QUALIFICATION.ITEMS (LABEL) VALUES ('rolled back')";
        command.ExecuteNonQuery();
        transaction.Rollback();
    }
    if (Convert.ToInt32(Scalar("SELECT COUNT(*) FROM MIGRATOR_QUALIFICATION.ITEMS")) != 1)
        throw new Exception("Rollback did not preserve the original row count.");
    if (Convert.ToInt32(Scalar("SELECT COUNT(*) FROM SYS.TABLE_COLUMNS WHERE SCHEMA_NAME='MIGRATOR_QUALIFICATION' AND TABLE_NAME='ITEMS'")) != 2)
        throw new Exception("Column catalog could not be read.");
    Console.WriteLine("HANA qualification passed: native .NET connection, DDL, identity, constraints, data, rollback and catalog access.");
}
finally { Execute("DROP SCHEMA MIGRATOR_QUALIFICATION CASCADE"); }
