using System.Data;
using DotNetProjects.Migrator.Framework;

namespace DotNetProjects.Migrator.Providers.Impl.Firebird;

public class FirebirdDialect : Dialect
{
    public override string GetCollationSql(string name) => "COLLATE " + QuoteIdentifier(name);

    // This flag controls MySQL-style inline INDEX syntax, not CREATE INDEX support.
    public override bool SupportsIndex => false;

    public FirebirdDialect()
    {
        RegisterColumnType(DbType.AnsiStringFixedLength, 8000, "CHAR($l)");
        RegisterColumnType(DbType.AnsiString, 8000, "CHAR($l)");
        RegisterColumnType(DbType.Binary, "BLOB");
        RegisterColumnType(DbType.Binary, 8000, "CHAR");
        RegisterColumnType(DbType.Boolean, "BOOLEAN");
        RegisterColumnType(DbType.Byte, "SMALLINT");
        RegisterColumnType(DbType.Currency, "DECIMAL(18,4)");
        RegisterColumnType(DbType.Date, "DATE");
        RegisterColumnType(DbType.DateTime, "TIMESTAMP");
        RegisterColumnType(DbType.DateTimeOffset, "TIMESTAMP");
        RegisterColumnType(DbType.Decimal, "DECIMAL");
        RegisterColumnTypeWithParameters(DbType.Decimal, "DECIMAL({precision},{scale})");
        RegisterColumnType(DbType.Double, "DOUBLE PRECISION"); //synonym for FLOAT(53)
        RegisterColumnType(DbType.Guid, "CHAR(38)");
        RegisterColumnType(DbType.Int16, "SMALLINT");
        RegisterColumnType(DbType.Int32, "INT");
        RegisterColumnType(DbType.Int64, "BIGINT");
        RegisterColumnType(DbType.Single, "REAL"); //synonym for FLOAT(24) 
        RegisterColumnType(DbType.StringFixedLength, "NCHAR(255)");
        RegisterColumnType(DbType.String, "VARCHAR(255) CHARACTER SET UNICODE_FSS");
        RegisterColumnType(DbType.String, 4000, "VARCHAR($l) CHARACTER SET UNICODE_FSS");
        RegisterColumnType(DbType.String, int.MaxValue, "BLOB SUB_TYPE TEXT");
        RegisterColumnType(DbType.Time, "TIME");

        RegisterColumnAttribute(ColumnAttribute.Identity, "GENERATED BY DEFAULT AS IDENTITY");

        this.RegisterUnsignedCompatible(DbType.Int16);
        this.RegisterUnsignedCompatible(DbType.Int32);
        this.RegisterUnsignedCompatible(DbType.Int64);
        this.RegisterUnsignedCompatible(DbType.Decimal);
        this.RegisterUnsignedCompatible(DbType.Double);
        this.RegisterUnsignedCompatible(DbType.Single);

        this.AddReservedWords("KEY", "TIMESTAMP", "VALUE");
    }


    public override ITransformationProvider GetTransformationProvider(Dialect dialect, string connectionString, string defaultSchema, string scope, string providerName)
    {
        return new FirebirdTransformationProvider(dialect, connectionString, scope, providerName);
    }

    public override ColumnPropertiesMapper GetColumnMapper(Column column)
    {
        var type = column.Size > 0 ? GetTypeName(column.Type, column.Size) : GetTypeName(column.Type);
        if (column.Precision.HasValue || column.Scale.HasValue)
        {
            type = GetTypeNameParametrized(column.Type, column.Size, column.Precision ?? 0, column.Scale ?? 0);
        }

        if (!IdentityNeedsType && column.IsIdentity)
        {
            type = string.Empty;
        }

        return new FirebirdColumnPropertiesMapper(this, type);
    }

    public override ITransformationProvider GetTransformationProvider(Dialect dialect, IDbConnection connection,
      string defaultSchema,
      string scope, string providerName)
    {
        return new FirebirdTransformationProvider(dialect, connection, scope, providerName);
    }
}
