using System;
using System.Data;
using System.Linq;
using DotNetProjects.Migrator.Framework;

namespace DotNetProjects.Migrator.Providers.Impl.Hana;

public class HanaDialect : Dialect
{
    public HanaDialect()
    {
        RegisterColumnType(DbType.Int16, "SMALLINT");
        RegisterColumnType(DbType.Int32, "INTEGER");
        RegisterColumnType(DbType.Int64, "BIGINT");
        RegisterColumnType(DbType.Byte, "TINYINT");
        RegisterColumnType(DbType.Boolean, "BOOLEAN");
        RegisterColumnType(DbType.Decimal, "DECIMAL(18, 4)");
        RegisterColumnType(DbType.Currency, "DECIMAL(18, 4)");
        RegisterColumnTypeWithParameters(DbType.Decimal, "DECIMAL({precision},{scale})");
        RegisterColumnType(DbType.Double, "DOUBLE");
        RegisterColumnType(DbType.Single, "REAL");
        RegisterColumnType(DbType.String, "NVARCHAR(255)");
        RegisterColumnType(DbType.String, 5000, "NVARCHAR($l)");
        RegisterColumnType(DbType.String, int.MaxValue, "NCLOB");
        RegisterColumnType(DbType.AnsiString, "VARCHAR(255)");
        RegisterColumnType(DbType.AnsiString, 5000, "VARCHAR($l)");
        RegisterColumnType(DbType.AnsiString, int.MaxValue, "CLOB");
        RegisterColumnType(DbType.StringFixedLength, "NCHAR(255)");
        RegisterColumnType(DbType.StringFixedLength, 5000, "NCHAR($l)");
        RegisterColumnType(DbType.AnsiStringFixedLength, "CHAR(255)");
        RegisterColumnType(DbType.AnsiStringFixedLength, 5000, "CHAR($l)");
        RegisterColumnType(DbType.Binary, "BLOB");
        RegisterColumnType(DbType.Binary, 5000, "VARBINARY($l)");
        RegisterColumnType(DbType.Date, "DATE");
        RegisterColumnType(DbType.Time, "TIME");
        RegisterColumnType(DbType.DateTime, "TIMESTAMP");
        RegisterColumnType(DbType.DateTime2, "TIMESTAMP");
        RegisterColumnAttribute(ColumnAttribute.Identity, "GENERATED BY DEFAULT AS IDENTITY");
    }
    public override bool TableNameNeedsQuote => true;
    public override bool ColumnNameNeedsQuote => true;
    public override bool ConstraintNameNeedsQuote => true;
    public override bool IdentityNeedsType => true;
    public override bool NeedsNullForNullableWhenAlteringTable => true;
    public override bool SupportsIndex => false;
    public override string QuoteTemplate => "\"{0}\"";
    public override string Quote(string name) => base.Quote(name);
    public override string Default(object value) => value switch
    {
        bool boolean => boolean ? "DEFAULT TRUE" : "DEFAULT FALSE",
        TimeSpan time when time >= TimeSpan.Zero && time < TimeSpan.FromDays(1) => "DEFAULT '" + time.ToString("c", System.Globalization.CultureInfo.InvariantCulture) + "'",
        byte[] bytes => "DEFAULT X'" + Convert.ToHexString(bytes) + "'",
        _ => base.Default(value)
    };
    public override ITransformationProvider GetTransformationProvider(Dialect dialect, string connectionString, string defaultSchema, string scope, string providerName) =>
        new HanaTransformationProvider(dialect, connectionString, defaultSchema, scope, providerName);
    public override ITransformationProvider GetTransformationProvider(Dialect dialect, IDbConnection connection, string defaultSchema, string scope, string providerName) =>
        new HanaTransformationProvider(dialect, connection, defaultSchema, scope);
}
