using System.Data;
using DotNetProjects.Migrator.Framework;

namespace DotNetProjects.Migrator.Providers.Impl.DB2;

public class DB2Dialect : Dialect
{
    // This flag controls MySQL-style inline INDEX syntax, not CREATE INDEX support.
    public override bool SupportsIndex => false;

    public DB2Dialect()
    {
        RegisterColumnType(DbType.AnsiStringFixedLength, "CHAR(255)");
        RegisterColumnType(DbType.AnsiString, "VARCHAR(255)");
        RegisterColumnType(DbType.StringFixedLength, "CHAR(255)");
        RegisterColumnType(DbType.String, "VARCHAR(255)");
        RegisterColumnType(DbType.Binary, "BLOB");
        RegisterColumnType(DbType.Boolean, "BOOLEAN");
        RegisterColumnType(DbType.Byte, "SMALLINT");
        RegisterColumnType(DbType.Currency, "DECIMAL(18,4)");
        RegisterColumnType(DbType.Date, "DATE");
        RegisterColumnType(DbType.DateTime, "TIMESTAMP");
        RegisterColumnType(DbType.DateTime2, "TIMESTAMP");
        RegisterColumnType(DbType.DateTimeOffset, "TIMESTAMP");
        RegisterColumnType(DbType.Decimal, "DECIMAL(18,5)");
        RegisterColumnTypeWithParameters(DbType.Decimal, "DECIMAL({precision},{scale})");
        RegisterColumnType(DbType.VarNumeric, "DECFLOAT(34)");
        RegisterColumnTypeWithParameters(DbType.VarNumeric, "DECFLOAT({precision})");
        RegisterColumnType(DbType.Double, "DOUBLE PRECISION");
        RegisterColumnType(DbType.Guid, "CHAR(36)");
        RegisterColumnType(DbType.Int16, "SMALLINT");
        RegisterColumnType(DbType.Int32, "INTEGER");
        RegisterColumnType(DbType.Int64, "BIGINT");
        RegisterColumnType(DbType.Single, "REAL");
        RegisterColumnType(DbType.Time, "TIME");
        RegisterColumnType(DbType.String, 32672, "VARCHAR($l)");
        RegisterColumnType(DbType.String, int.MaxValue, "CLOB");
        RegisterColumnType(DbType.AnsiString, 32672, "VARCHAR($l)");
        RegisterColumnType(DbType.AnsiString, int.MaxValue, "CLOB");
        RegisterColumnType(DbType.StringFixedLength, 255, "CHAR($l)");
        RegisterColumnType(DbType.AnsiStringFixedLength, 255, "CHAR($l)");
        RegisterColumnAttribute(ColumnAttribute.Identity, "GENERATED BY DEFAULT AS IDENTITY");
    }

    public override ColumnPropertiesMapper GetColumnMapper(Column column)
    {
        var type = column.Size > 0 ? GetTypeName(column.Type, column.Size) : GetTypeName(column.Type);
        if (column.Precision.HasValue || column.Scale.HasValue)
            type = GetTypeNameParametrized(column.Type, column.Size, column.Precision ?? 18, column.Scale ?? 0);
        return new NativeColumnMapper(this, type);
    }

    private sealed class NativeColumnMapper(Dialect dialect, string type) : ColumnPropertiesMapper(dialect, type)
    {
        public override void MapColumnProperties(Column column)
        {
            Name = column.Name;

            var parts = new System.Collections.Generic.List<string>();
            AddName(parts);
            AddType(parts);
            AddCollation(column, parts);
            AddUnsigned(column, parts);
            AddIdentityAgain(column, parts);
            AddDefaultValue(column, parts);
            if (!column.IsNullable)
                parts.Add("NOT NULL");

            _ColumnSql = string.Join(" ", parts);
        }
    }

    public override ITransformationProvider GetTransformationProvider(Dialect dialect, string connectionString,
        string defaultSchema, string scope, string providerName)
    {
        return new DB2TransformationProvider(dialect, connectionString, scope, providerName);
    }

    public override ITransformationProvider GetTransformationProvider(Dialect dialect, IDbConnection connection,
        string defaultSchema,
        string scope, string providerName)
    {
        return new DB2TransformationProvider(dialect, connection, scope, providerName);
    }
}
