name: .NET Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
           9.0.x
    - name: Restore dependencies
      run: |
        dotnet restore Migrator.slnx
    - name: Build
      run: |
        dotnet build Migrator.slnx
    - name: Test
      run: |
        dotnet test Migrator.slnx